### ISSUE TITLE
GitのGUIツール　Sourcetree

### ISSUE THREAD

**Issue by inamine007** [inamine007/petit_hackathon_1#2]
# 特徴
- Gitのcommit履歴などがすぐに見れる。
- コミット、プッシュ、チェックアウトなどの操作がクリックでできる。
- Gitの一連の流れを画面で見ることでイメージがしやすくなる。

<img width="1440" alt="スクリーンショット 2022-09-04 14 39 22" src="https://user-images.githubusercontent.com/60652558/188299372-77f5756c-1466-4a22-9c15-ed7b3ef09c86.png">

**Comment by TakakoYamaguchi** [comment]
<img width="1053" alt="スクリーンショット 2022-09-04 22 15 12" src="https://user-images.githubusercontent.com/106862064/188315415-c7c1e557-1082-423b-a152-9f138f664b97.png">

**Comment by hayato-f** [comment]
![Uploading スクリーンショット 2022-09-05 18.30.30.png…]()

**Comment by hayato-f** [comment]
<img width="1440" alt="スクリーンショット 2022-09-05 18 28 34" src="https://user-images.githubusercontent.com/104083127/188421421-ff5913ff-228f-4155-b6ca-bfd89e07f7ee.png">
